# -*- coding: utf-8 -*-
"""NLP miniproject

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cmnQP02uTOPPWhHD-w9_xIPtenuhRP96
"""

!apt-get install -y default-jre tesseract-ocr > /dev/null
!pip install -q PyMuPDF pdfminer.six tabula-py pandas Pillow python-docx pytesseract

#Import Libraries
import fitz  # PyMuPDF
import tabula
import pandas as pd
from pdfminer.high_level import extract_text as pdf_extract_text
import docx
from PIL import Image
import io
import pytesseract
from google.colab import files

# PDF Processing

def extract_pdf_text_pymupdf(file_path):
    """Extracts text from a PDF's text layer using PyMuPDF."""
    try:
        with fitz.open(file_path) as doc:
            text = "".join(page.get_text() for page in doc)
        return text.strip()
    except Exception as e:
        print(f"  Error extracting text with PyMuPDF: {e}")
        return None

def perform_ocr_on_pdf(file_path):
    """Performs OCR on a PDF, treating each page as an image."""
    print("\n### Text (from OCR Tesseract):")
    try:
        doc = fitz.open(file_path)
        full_text = ""
        for page in doc:
            pix = page.get_pixmap(dpi=300)  # Render page to an image
            img = Image.open(io.BytesIO(pix.tobytes()))
            text = pytesseract.image_to_string(img)
            full_text += text + "\n"
        print(full_text or "OCR did not find any text.")
    except Exception as e:
        print(f"  Error during OCR: {e}")

def extract_pdf_images(file_path):
    """Extracts embedded images from a PDF."""
    print("\n### Embedded Images:")
    try:
        doc = fitz.open(file_path)
        image_found = False
        for page_num, page in enumerate(doc):
            for img_index, img in enumerate(page.get_images(full=True)):
                xref = img[0]
                base_image = doc.extract_image(xref)
                image_bytes = base_image["image"]
                image = Image.open(io.BytesIO(image_bytes))
                saved_path = f"extracted_{file_path}_p{page_num+1}_img{img_index+1}.png"
                image.save(saved_path)
                print(f"  Image saved as '{saved_path}'")
                image_found = True
        if not image_found:
            print("  No embedded images found.")
    except Exception as e:
        print(f"  Error extracting images: {e}")

def extract_pdf_tables(file_path):
    """Extracts tables from a PDF using tabula-py."""
    print("\n### Tables:")
    try:
        tables = tabula.read_pdf(file_path, pages='all', silent=True)
        if tables:
            print(f"  Found {len(tables)} table(s).")
            for i, df in enumerate(tables):
                print(f"\n--- Table {i+1} ---")
                display(df)
        else:
            print("  No tables found.")
    except Exception as e:
        print(f"  Error extracting tables: {e}")

#Docx Processing
def extract_docx_text(doc):
    """Extracts all paragraph text from a DOCX document."""
    print("### Text:")
    try:
        full_text = [para.text for para in doc.paragraphs]
        print('\n'.join(full_text) or "No text found in paragraphs.")
    except Exception as e:
        print(f"  Error extracting text: {e}")

def extract_docx_tables(doc):
    """Extracts tables from a DOCX document."""
    print("\n### Tables:")
    try:
        if doc.tables:
            print(f"  Found {len(doc.tables)} table(s).")
            for i, table in enumerate(doc.tables):
                print(f"\n--- Table {i+1} ---")
                data = [[cell.text for cell in row.cells] for row in table.rows]
                df = pd.DataFrame(data[1:], columns=data[0] if data else None)
                display(df)
        else:
            print("  No tables found.")
    except Exception as e:
        print(f"  Error extracting tables: {e}")

def extract_docx_images(doc, file_name):
    """Extracts images from a DOCX document."""
    print("\n### Images:")
    try:
        image_found = False
        image_parts = [part for rel in doc.part.rels.values() if "image" in rel.target_ref for part in (rel.target_part,)]
        for i, image_part in enumerate(image_parts):
            image_bytes = image_part.blob
            image = Image.open(io.BytesIO(image_bytes))
            saved_path = f"extracted_{file_name}_img{i+1}.{image.format.lower()}"
            image.save(saved_path)
            print(f"  Image saved as '{saved_path}'")
            image_found = True
        if not image_found:
            print("  No images found.")
    except Exception as e:
        print(f"  Error extracting images: {e}")


def process_pdf(file_name):
    """Manages the extraction process for a PDF file, with OCR fallback."""
    print(f"\n--- Processing PDF: {file_name} ---")

    # First, try to extract text from the text layer
    print("### Text (from PyMuPDF):")
    standard_text = extract_pdf_text_pymupdf(file_name)
    print(standard_text or "No text layer found.")

    # If no text was found, it's likely an image-based PDF, so run OCR
    if not standard_text:
        perform_ocr_on_pdf(file_name)

    # Proceed with table and image extraction
    extract_pdf_tables(file_name)
    extract_pdf_images(file_name)

def process_docx(file_name):
    """Manages the extraction process for a DOCX file."""
    print(f"\n--- Processing DOCX: {file_name} ---")
    try:
        doc = docx.Document(file_name)
        extract_docx_text(doc)
        extract_docx_tables(doc)
        extract_docx_images(doc, file_name)
    except Exception as e:
        print(f"Failed to open and process DOCX file. Error: {e}")

#Main
print("Please upload your PDF or DOCX file(s)...")
uploaded = files.upload()

if not uploaded:
    print("\nNo files were uploaded. Please run the cell again.")
else:
    for file_name in uploaded.keys():
        if file_name.lower().endswith('.pdf'):
            process_pdf(file_name)
        elif file_name.lower().endswith('.docx'):
            process_docx(file_name)
        else:
            print(f"\nFile '{file_name}' is not a supported type (must be .pdf or .docx).")
    print(f"\n--- Processing complete for all uploaded files. ---")

import re
import spacy
from google.colab import files

try:
    nlp = spacy.load("en_core_web_sm")
except OSError:
    print("Downloading spaCy model...")
    from spacy.cli import download
    download("en_core_web_sm")
    nlp = spacy.load("en_core_web_sm")

def extract_name(text):

    doc = nlp(text)
    for ent in doc.ents:
        if ent.label_ == "PERSON":
            return ent.text
    return None

def extract_email(text):

    pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
    match = re.search(pattern, text)
    return match.group(0) if match else None

def extract_phone_number(text):

    pattern = r'(\(?\+?\d{1,3}\)?[\s.-]?)?\(?(\d{3})\)?[\s.-]?(\d{3})[\s.-]?(\d{4})'
    match = re.search(pattern, text)
    return match.group(0).strip() if match else None

def extract_linkedin(text):

    pattern = r'https?:\/\/(www\.)?linkedin\.com\/in\/[A-Za-z0-9_-]+\/?'
    match = re.search(pattern, text)
    return match.group(0) if match else None


def extract_skills(text, skills_db):

    found_skills = set()
    doc = nlp(text.lower())
    for token in doc:
        if token.text in skills_db:
            found_skills.add(token.text)

    for skill in skills_db:
        if ' ' in skill and skill in text.lower():
            found_skills.add(skill)
    return list(found_skills)

def extract_structured_data(raw_text):

    SKILLS_DB = [
        'python', 'java', 'c++', 'sql', 'javascript', 'react', 'angular', 'vue',
        'nodejs', 'express', 'mongodb', 'postgresql', 'mysql', 'docker', 'kubernetes',
        'aws', 'azure', 'gcp', 'terraform', 'ansible', 'jenkins', 'git', 'jira',
        'fastapi', 'django', 'flask', 'machine learning', 'data analysis', 'nlp'
    ]

    extracted_data = {
        "name": extract_name(raw_text),
        "email": extract_email(raw_text),
        "phone": extract_phone_number(raw_text),
        "linkedin": extract_linkedin(raw_text),
        "skills": extract_skills(raw_text, SKILLS_DB)
    }

    return extracted_data

if 'raw_texts' in locals() and raw_texts:
    for file_name, raw_text in raw_texts.items():
        print(f"\n--- Processing File: {file_name} for structured data extraction ---")

        if raw_text:
            # 1. Extract structured data from the raw text
            structured_data = extract_structured_data(raw_text)

            # 2. Display the results
            print("\n--- Extracted Information ---")
            print(f"  Name:     {structured_data.get('name', 'Not Found')}")
            print(f"  Email:    {structured_data.get('email', 'Not Found')}")
            print(f"  Phone:    {structured_data.get('phone', 'Not Found')}")
            print(f"  LinkedIn: {structured_data.get('linkedin', 'Not Found')}") # Display LinkedIn
            print(f"  Skills:   {', '.join(structured_data.get('skills', [])) or 'None Found'}")
        else:
            print("No raw text available for structured data extraction.")

    print(f"\n--- Structured data extraction complete for all uploaded files. ---")
else:
    print("Please run the first cell to upload files and extract raw text.")

print("Installing dependencies... (This may take a minute)")
!apt-get install -y default-jre tesseract-ocr > /dev/null
!pip install -q PyMuPDF python-docx Pillow spacy pytesseract
!python -m spacy download en_core_web_sm > /dev/null
print("Installation complete.")

import re
import io
import fitz  # PyMuPDF
import docx
from PIL import Image
import spacy
import pytesseract
from google.colab import files

try:
    nlp = spacy.load("en_core_web_sm")
except OSError:
    print("Downloading spaCy model...")
    from spacy.cli import download
    download("en_core_web_sm")
    nlp = spacy.load("en_core_web_sm")

def extract_name(text):
    """Extracts the full name from the text using spaCy's NER."""
    doc = nlp(text)
    for ent in doc.ents:
        if ent.label_ == "PERSON":
            return ent.text
    return None

def extract_email(text):
    """Extracts the email address using a regular expression."""
    pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
    match = re.search(pattern, text)
    return match.group(0) if match else None

def extract_phone_number(text):
    """Extracts a phone number using a regular expression."""
    pattern = r'(\(?\+?\d{1,3}\)?[\s.-]?)?\(?(\d{3})\)?[\s.-]?(\d{3})[\s.-]?(\d{4})'
    match = re.search(pattern, text)
    return match.group(0).strip() if match else None

def extract_linkedin(text):
    """Extracts a LinkedIn profile URL using a regular expression."""
    pattern = r'https?:\/\/(www\.)?linkedin\.com\/in\/[A-Za-z0-9_-]+\/?'
    match = re.search(pattern, text)
    return match.group(0) if match else None


def extract_skills(text, skills_db):
    """Extracts skills from the text based on a predefined list."""
    found_skills = set()
    doc = nlp(text.lower())
    for token in doc:
        if token.text in skills_db:
            found_skills.add(token.text)
    # Check for multi-word skills (phrases)
    for skill in skills_db:
        if ' ' in skill and skill in text.lower():
            found_skills.add(skill)
    return list(found_skills)

def extract_structured_data(raw_text):
    """Cleans and extracts key information from raw resume text."""

    # A sample database of skills. You can greatly expand this list.
    SKILLS_DB = [
        'python', 'java', 'c++', 'sql', 'javascript', 'react', 'angular', 'vue',
        'nodejs', 'express', 'mongodb', 'postgresql', 'mysql', 'docker', 'kubernetes',
        'aws', 'azure', 'gcp', 'terraform', 'ansible', 'jenkins', 'git', 'jira',
        'fastapi', 'django', 'flask', 'machine learning', 'data analysis', 'nlp'
    ]

    extracted_data = {
        "name": extract_name(raw_text),
        "email": extract_email(raw_text),
        "phone": extract_phone_number(raw_text),
        "linkedin": extract_linkedin(raw_text),
        "skills": extract_skills(raw_text, SKILLS_DB)
    }

    return extracted_data



def get_raw_text_from_file(file_name, file_bytes):
    """
    Extracts raw text from a file (PDF or DOCX), using OCR if necessary.
    """
    text = ""
    try:
        if file_name.lower().endswith('.pdf'):
            with fitz.open(stream=file_bytes, filetype="pdf") as doc:
                text = "".join(page.get_text() for page in doc)

            # If no text layer, it's an image-based PDF; run OCR
            if not text.strip():
                print("INFO: No text layer found. Running OCR...")
                with fitz.open(stream=file_bytes, filetype="pdf") as doc:
                    for page in doc:
                        pix = page.get_pixmap(dpi=300)
                        img = Image.open(io.BytesIO(pix.tobytes()))
                        text += pytesseract.image_to_string(img)

        elif file_name.lower().endswith('.docx'):
            doc = docx.Document(io.BytesIO(file_bytes))
            text = "\n".join([para.text for para in doc.paragraphs])

    except Exception as e:
        print(f"ERROR: Could not parse file '{file_name}': {e}")

    return text.strip()



print("\nPlease upload your resume file(s) (PDF or DOCX)...")
uploaded_files = files.upload()

if not uploaded_files:
    print("\nNo files were uploaded.")
else:
    for file_name, file_content in uploaded_files.items():
        print(f"\n--- Processing File: {file_name} ---")


        raw_text = get_raw_text_from_file(file_name, file_content)

        if raw_text:
            print("\n### Raw Text Extracted:")
            print(raw_text)
            structured_data = extract_structured_data(raw_text)


            print("\n--- Extracted Information ---")
            print(f"  Name:     {structured_data.get('name', 'Not Found')}")
            print(f"  Email:    {structured_data.get('email', 'Not Found')}")
            print(f"  Phone:    {structured_data.get('phone', 'Not Found')}")
            print(f"  LinkedIn: {structured_data.get('linkedin', 'Not Found')}")
            print(f"  Skills:   {', '.join(structured_data.get('skills', [])) or 'None Found'}")
        else:
            print("Could not extract any text from the document.")

    print(f"\n--- Processing complete for all uploaded files. ---")