"""mvp_insights_status_fields

Revision ID: 07d09b4821e0
Revises: c6a532cf0a65
Create Date: 2025-10-06 22:40:04.070192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07d09b4821e0'
down_revision: Union[str, Sequence[str], None] = 'c6a532cf0a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the PostgreSQL ENUM type explicitly before adding the column
    status_enum = postgresql.ENUM('submitted', 'processing', 'processed', 'failed', name='status')
    status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('applicants', sa.Column('status', status_enum, nullable=True))
    op.add_column('insights', sa.Column('sentiment_score', sa.Float(), nullable=True))
    op.add_column('insights', sa.Column('activity_score', sa.Float(), nullable=True))
    op.add_column('insights', sa.Column('top_endorsed_skills', sa.JSON(), nullable=True))
    op.add_column('insights', sa.Column('projects', sa.JSON(), nullable=True))
    op.add_column('insights', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('insights', sa.Column('consistency_flags', sa.JSON(), nullable=True))
    op.add_column('insights', sa.Column('kb_namespace', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insights', 'kb_namespace')
    op.drop_column('insights', 'consistency_flags')
    op.drop_column('insights', 'experience_years')
    op.drop_column('insights', 'projects')
    op.drop_column('insights', 'top_endorsed_skills')
    op.drop_column('insights', 'activity_score')
    op.drop_column('insights', 'sentiment_score')
    op.drop_column('applicants', 'status')
    # Drop the ENUM type if no longer used
    status_enum = postgresql.ENUM('submitted', 'processing', 'processed', 'failed', name='status')
    status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
